### ISSUE TITLE
will we reapply for this fall 2018?

### ISSUE THREAD

**Issue by RMHogervorst** [ThinkR-open/isc-proposal#9]
https://www.r-consortium.org/announcement/2018/09/25/fall-2018-isc-call-for-proposals

**Comment by ColinFay** [comment]
Hey @RMHogervorst, 

Unfortunately, the reason given for us not being selected is that even if the project seemed interesting, Neo4J doesn't seem that much widespread among the R users, and I guess for now it's still the case :/

**Comment by RMHogervorst** [comment]
ah! I missed that part. Too bad!
